### ISSUE TITLE
Http Web Service Example which takes json input and outputs json.

### ISSUE THREAD

**Issue by KrishnaST** [softindex/datakernel#12]
Not a issue. Please provide a working example for a web service which takes json input and outputs json.

**Comment by Fly-Style** [comment]
Hi, @KrishnaST!
We already have some prepared examples with JSON messaging. 
Take a look at [To Do List](https://datakernel.io/docs/core/tutorials/todo-list-tutorial.html) example. You can find example sources [here](https://github.com/softindex/datakernel/tree/master/examples/tutorials/advanced-react-integration).
Does this example suit you?
