### ISSUE TITLE
Examples with commonly used components

### ISSUE THREAD

**Issue by josepowera** [softindex/datakernel#13]
For a framework that puts "SPEED" first it would be great to also show some examples with commonly used components like:
Aerospike (https://aerospike.com/docs/client/java/usage/async/index.html)
Redis (https://lettuce.io/core/release/reference/#asynchronous-api.examples) and 
Kafka, 
Grpc clients.

Also because Aerospike client and Redis client have their own EventLoops and combinantion of CompletableFuture and datakernel Promises is important to use existing java component ecosystem.

**Comment by Fly-Style** [comment]
Hi, @josepowera! I am glad to see your message here.
You can check out our benchmarks of our RPC ([up to 17-18 Mrps](https://github.com/softindex/datakernel/blob/master/examples/cloud/rpc/src/main/java/RpcBenchmark.java)), promises (~ [100MRps](https://github.com/softindex/datakernel/tree/master/examples/benchmarks/src/main/java/io/datakernel/promise)), memcache client/server implementations ([up to 10 Mrps](https://github.com/softindex/datakernel/blob/master/examples/cloud/rpc/src/main/java/MemcacheRpcBenchmark.java)), etc.
To be honest, it is difficult to compare our tools with Redis : its official [doc](https://redis.io/topics/benchmarks) provides 80 Krps / 700 Krps depending on the mode. 

Also, with DataKernel it is easy to create your own app-specific server with outstanding performance: for example, check our implementation of [Memcache](https://github.com/softindex/datakernel/tree/master/cloud-memcache/src/main/java/io/datakernel/memcache) server, with its client-server benchmark at 10Mrps on single CPU core.

Nevertheless, the raw speed is not the only advantage of DataKernel. The main goal is to give you a simple but comprehensive solution ([DI](https://datakernel.io/docs/core/di.html), [I/O core](https://datakernel.io/docs/core/csp.html), [HTTP](https://datakernel.io/docs/core/http.html), [RPC](https://datakernel.io/docs/cloud/rpc.html)) which allows to build applications of any complexity, ranging from web apps to high-performance scalable backend microservices solutions.
