### ISSUE TITLE
codegen: ExpressionToString NullPointerException

### ISSUE THREAD

**Issue by Neiko2002** [softindex/datakernel#6]
The generated code of the ExpressionToString class produces a NullPointerException at runtime if one of the appended objects is null. I think it would be better to check for null and append the String "null" to the underlying StringBuilder.

In my case, I was creating a new class containing non-primitive type fields, those fields will got initialized with null and caused my toString method to throw a NullPointerException.

**Comment by lightZebra** [comment]
Thanks for the issue, it’s fixed(acf2367), ExpressionToString will print "null" for non-primitive type fields with null value

**Comment by Neiko2002** [comment]
Works like a charm. Thank you.
