### ISSUE TITLE
cube module missing from maven central

### ISSUE THREAD

**Issue by drusifer** [softindex/datakernel#8]
Hi I think there's a minor issue with the pom.xml for the cube module in 1.1.3 which is causing it to not get published correctly.  I'm not certain but I think it has something to do with the override of the [version with version-snapshot](https://github.com/softindex/datakernel/blob/v1.1.3/cube/pom.xml#L14).  Any ideas?

**Comment by dvolvach** [comment]
Resolved in later versions.
