### ISSUE TITLE
[Documentation] "... not found" or problem when importing with maven

### ISSUE THREAD

**Issue by jjerphan** [softindex/datakernel#9]
Hi.

There is a problem with the documentation [here](http://datakernel.io/docs/installation.html) and [there](http://datakernel.io/docs/getting-started.html#step-by-step) that deals with versions of datakernel.

It is indicated to use the `2.0.9-SNAPSHOT` version, but the actual one is `2.4.0-SNAPSHOT`.
```xml
<dependency>
    <groupId>io.datakernel</groupId>
    <artifactId>datakernel-http</artifactId>
    <version>2.0.9-SNAPSHOT</version>
</dependency>
```
and 

```xml
<dependency>
     <groupId>io.datakernel</groupId>
     <artifactId>datakernel-eventloop</artifactId>
     <version>2.0.9-SNAPSHOT</version>
</dependency>
```
should be replaced accordingly -- at least that is what I've done in order for my project to use datakernel.

**Comment by lightZebra** [comment]
We have fixed docs for branch 2.0:
http://datakernel.io/docs/installation.html
http://datakernel.io/docs/getting-started.html#installation
Also, soon we’ll be updating docs to be consistent with current master, which is branch 2.5.
